### ISSUE TITLE
Download Dalhousie Collections

### ISSUE THREAD

**Issue by ianmilligan1** [web-archive-group/WALK#53]
Now that we have an MOU with them. 

- [x] #5925 Trial Collection
- [x] #6275 Dalhousie University 200th Anniversary
- [x] #6280 Bob Fournier
- [x] #6566 Halifax Regional Municipality Documents
- [x] #6653 Ransom Myers
- [x] #6671 TEST - Dalhousie Fellows of the Royal Society of Canada
- [x] #7485 Nova Scotia Municipal Governments
- [x] #7515 #homesnothondas Tweets (Homes not Hondas)
- [x] #8155 Mi'kmaq History and Culture
- [x] #8369 Dalhousie University 200th Anniversary (1818-2018)

**Comment by ianmilligan1** [comment]
@ruebot Just pinging as requested. 😄

**Comment by ruebot** [comment]
_downloading_

**Comment by ruebot** [comment]
Done.

**Comment by ianmilligan1** [comment]
🎉
